<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LCCU5LL" failures="1" tests="4" name="Test" time="53.555" errors="0" timestamp="2021-04-28T13:58:46 MDT">
  <testcase classname="tests.twoTest" name="twotest" time="12.571"/>
  <testcase classname="tests.threeTest" name="threetest" time="8.821">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.threeTest.threetest(threeTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- threetest -->
  <testcase classname="tests.LoginTest" name="login" time="5.58"/>
  <testcase classname="tests.LoginTest" name="login" time="5.889"/>
</testsuite> <!-- Test -->
